### ISSUE TITLE
Does this repo work at all???

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/jtag2updi#3]
I have been getting feedback from multiple customers that the code in here does not work when installed on a nano...

@Dlloydev - Are you sure that what you PR'ed to me worked? Does this code work for you?

**Comment by SpenceKonde** [comment]
(also, didn't realize until now that issues weren't enabled here!)

**Comment by Dlloydev** [comment]
I'll upload your code to a nano and give it a workout to see if I can find anything.
I tested my repo (prior to the pull) successfully on several chips.
Should have a report later tonight.

**Comment by Dlloydev** [comment]
OK, did a lot of testing, 3 jtag2updi repos: SpenceKonde, Dlloydev, Eltangas
Tested UPDI Mode only, got identical results on all 3 repos.
I used megaTinyCore 2.1.5 via Boards Manager ... got warnings for the ATtiny212 and 412 parts.

I did some HV programming tests with your repo and mine (identical) using the Nano HV  UPDI Programmer in PCHV Mode and both repos work OK. Note that with the default chip settings, its possible to brick the target when using PORTC power (T5V). Happened with the ATtiny212 and 412 parts, (no optiboot) using Upload Using Programmer.
If this happens, the remedy is to use 5V power on the 6-pin header.

Note that the default UPDI baudrate is 100Kbps. I had changed this earlier when investigating a SYNC problem using the Power Debugger and Snap Debugger (). It now matches the default baudrate of the Power Debugger ... forgot to change it back to 225Kbps.

**Test Results (same for all 3 repos):**

- Arduino 1.8.13
- megaTinyCore 2.1.5 via Boards Manager
- Arduino Nano HV UPDI Programmer (UPDI Mode)
- UPDI Baudrate 100Kbps (default)
- Chip Settings: Clock 20MHz, default timer, Support serial event - no,  BOD 1.8V, BOD Mode - Disabled, EEPROM Retained, SUT 8ms, UPDI Pin - UPDI
- Nano Programmer Auto Reset: Disabled (4.7µF from reset to GND)

Target Device | Description | UPDI Series Resistance | Burn Bootloader (Optiboot) | Upload Using Programmer (Optiboot) | Burn Bootloader | Upload Using Programmer
-- | -- | -- | -- | -- | -- | --
ATtiny212N | On SOIC-8 to DIP-8 adapter | 1.2K | Success | Success 1 | Success | Success 1
ATtiny412F | On SOIC-8 to DIP-8 adapter | 1.2K | Success | Success 1 | Success | Success 1
ATtiny1604N | Azzy's Electronics Dev. board | 1.2K | Success | Success | Success | Success
ATtiny1604N | Azzy's Electronics Dev. board | 1.2K + 4.7K | Success | Success | Success | Success
ATtiny1606F | Azzy's Electronics Dev. board | 1.2K | Success | Success | Success | Success
ATtiny1606F | Azzy's Electronics Dev. board | 1.2K + 4.7K | Success | Success | Success | Success
ATtiny3216N | On SOIC-20 to DIP-20 adapter | 1.2K | Success | Success | Success | Success

**Success 1:** Multiple warnings: <command-line>:0:9: warning: ISO C++11 requires whitespace after the macro name

**Comment by stonehippo** [comment]
@Dlloydev have you test this with a Pro Mini set up as a UPDI programmer? If I try to use `master`, I'm getting a fail:

```
avrdude: jtagmkII_getsync(): sign-on command: status -1
```

As a test, I checked out 85139ba, which was the last commit @SpenceKonde made prior any commits from #1, and things seem to work as expected. I haven't tried to see where things might be broken further in the master branch, but it would be great to figure where things have gone wrong. If I find some time, I'll see if I can pin down the exact issue.

**Comment by stonehippo** [comment]
@SpenceKonde @Dlloydev quick update: I decided to try out https://github.com/dlloydev/jtag2updi, just in case. And things seemed to work just fine with the HEAD of current master branch. I pulled both repos and diff'ed them and it's fair to say there's stuff that doesn't match up (even when ignoring white space diffs). I've got to put this down for a bit, but it might be worth taking a look at the differences, since it seems like the current HEAD here is indeed broken.

**Comment by SpenceKonde** [comment]
Any changes that went into his repo were supposed to get pulled into this one, goddamnit

**Comment by Dlloydev** [comment]
The only difference I can detect is in the file size for jtag2updi.cpp (6.03 KB SpenceKonde vs 6.22 KB Dlloydev) which appears to be due to white space? I didn't visually detect any code differences, but I wish I knew how to do a diff just on one file (still green at using git).

Thanks for your tests @stonehippo. I'd like to be able to reproduce what you're finding, so I'll dig out my Pro Mini and also test the Nano stand alone without the HV PCB. I'll use the UPDI programmer circuit with direct connect to 5V and 470 ohm series resistance in the UPDI signal. Should have some time later today and tomorrow ... will report back with results.

**Comment by Dlloydev** [comment]
**Solution - configure A6 and A7 as follows:**
![nano_updi_prog](https://user-images.githubusercontent.com/63488701/100675407-e8ae8700-3334-11eb-9dca-547f79e68e57.png)
Or you can eliminate the A6 and A7 jumpers if using the Eltangas jtag2updi firmware.

**Problem:**

Analog inputs A6 (overload sense) and A7 (HV programmer Mode) are left floating for users that are just needing a simple UPDI programmer. Right now, the firmware always reads these inputs as it doesn't know if the user is building a UPDI only or HV UPDI programmer. Note that these inputs are analog only so configuring them with jumpers is safe.

**Test Results:**

A6 left floating usually drifts high and triggers overload status - continuous flashing of yellow LED at 4Hz. The code is unusable because pressing reset just re-starts the problem.

A7 left floating usually drifts high and triggers PCHV Mode. I jumpered A6 to 5V to test if there's any programming implications. I found that "Burn Bootloader" may require 2 programming attempts for success as it goes into a weird toggle mode ... pass/fail/pass/fail etc. I've seen this before when using HV settings on an HV UPDI programmer while the UPDI pin on the target is already in UPDI mode. This is strangely similar to the known issues and workarounds [here](https://microchipdeveloper.com/mplabx:avr-updi-high-voltage).

Note: Adding a 4.7µF or 10µF capacitor from the Nano's reset pin to GND will greatly speed things up on the first programming run (Burn Bootloader or Upload Using Programmer) after power up. Remember to disconnect it before updating the programmer's firmware. You'll notice that on power up, the capacitor holds the reset line stable and the Nano's yellow LED will only go through one pulse sequence, not 5 or 6 pulse bursts over a much longer period of time. It should also filter glitches that may occur on the Nano's DTR signal.

**Comment by stonehippo** [comment]
Interesting. I want getting the flashing LED/floating pin issue with current master on your fork, @Dlloydev, but was with master on here (with the Pro Mini). The unit I converted is a bit of a pain to modify, unless I want to strip off the heat shrink in encased it in. Maybe I'll grab another one of the Minis I have on hand and breadboard it out to try you solution.

**Comment by SpenceKonde** [comment]
Huh - so now this code does not support a basic nano programmer? That is not good.

**Comment by Dlloydev** [comment]
> The unit I converted is a bit of a pain to modify, unless I want to strip off the heat shrink in encased it in.
 
If you only need a UPDI programmer and not the HV stuff, then with your converted board you could just use the [Eltangas](https://github.com/ElTangas/jtag2updi) firmware. If possible, I recommend adding the 4.7µF or 10µF capacitor to the reset pin.

**Comment by Dlloydev** [comment]
> Huh - so now this code does not support a basic nano programmer? That is not good.

Well, the code supports it if the hardware configures it.

I'll have to think about if there's another hardware method  ... maybe a spare pin with pullup enabled to have UPDI mode as default, but that could render any pre-built HV programmer useless unless re-configured.

I don't know if there's any automatic way this could be done in code other than testing for the __AVR_ATmega328P__ define.

**Comment by SpenceKonde** [comment]
There, both versions should now be supported with the same codebase, which one you get is now configured by a #define in sys.h (sadly, it doesn't look like the other files can see #defines in the .ino - it would be maximally user-friendly if that's where the option was)

**Comment by SpenceKonde** [comment]
It would be ideal to have a way to support it with the same binary - but people generally know if there's an HV programmer connected to their nano being used as UPDI programmer when they are uploading the code, I reckon...

**Comment by Dlloydev** [comment]
Wow, that was fast!

So I could test for the USE_HV_PROGRAMMING define in all the HV functions, then if not found, the code becomes a UPDI progrmmer. My repo could have this define active (HV UPDI Programmer as default) and your repo could have this define commented out (UPDI Programmer as default).  Is this what you envision?

**Comment by SpenceKonde** [comment]
I think I got them all in my repo at least to where the result will work - feel free to clean up after me, I just wanted to get it to state I knew would work quickly. 

Also, your code doesn't compile for the DA-series ;-)

**Comment by Dlloydev** [comment]
> Also, your code doesn't compile for the DA-series ;-)

Oh, wow Awesome! ! (looks like your repo now has the solution to that little problem)
